on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
#   install all the dependencies     
    - name: Install dependencies
      run: |
        npm install
#     launch the unit testing 
    - name: Test the code
      run: |
        npm test
#     build and deploy the new version of the image
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: momenas777/iowaves
        tags: server, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#    Notify all the team for the new version     
    - name: Send mail
      uses: juanformoso/action-send-mail@1
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        # Literal body:
        body: Build job of ${{github.repository}} completed successfully!
        # Read file contents as body:
        to: mehdinasri232@gmail.com,nasrimehdi96@gmail.com

        from: ${{secrets.MAIL_USERNAME}}
        # Optional content type (defaults to text/plain):
        content_type: text/html
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
